# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""Spawn `claude -p --output-format stream-json` and yield parsed stream-json
events. Pair with translate() to get AG-UI events.

Sandbox-BLIND: the caller builds the argv and may pass a custom `exec`. The same
function covers every substrate because only the argv differs:
    local:  stream_claude(["claude", "-p", prompt, "--output-format", "stream-json", ...])
    DinD:   stream_claude(["docker", "exec", "-i", container, "claude", "-p", ...])
A microVM/E2B runner just builds a different argv (or passes its own `exec`).

This is the spawn+parse+reap loop that was copy-pasted as claude_runner.py /
dind.py's exec_claude across apps; it lives here now so there is one copy.
"""
from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator, Sequence


async def stream_claude(
    argv: Sequence[str],
    *,
    exec=asyncio.create_subprocess_exec,
    reap_timeout: float = 2.0,
) -> AsyncIterator[dict]:
    """Run `argv`, yield each stdout line parsed as JSON (a stream-json event).
    A non-JSON line is surfaced as `{"type": "raw", "line": ...}`. On
    close/cancel the process is reaped (terminate, then kill after
    `reap_timeout`). stderr is discarded so it can't corrupt the NDJSON stream.
    """
    proc = await exec(*argv, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.DEVNULL)
    assert proc.stdout is not None
    try:
        while True:
            line = await proc.stdout.readline()
            if not line:
                break
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                yield {"type": "raw", "line": line.decode(errors="replace").rstrip()}
    finally:
        if proc.returncode is None:
            proc.terminate()
            try:
                await asyncio.wait_for(proc.wait(), timeout=reap_timeout)
            except asyncio.TimeoutError:
                proc.kill()
                await proc.wait()
