# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""Drive one agent turn: fold an AG-UI event stream into a RunLog as a
background task, with the standard terminal handling.

The app builds the event stream (typically `translate(runner.exec_claude(...))`)
and owns prompt-building, the sandbox, and any queue/next-turn logic. This just
appends every event to the log and guarantees a terminal event on cancel/error.
"""
from __future__ import annotations

import time
from collections.abc import AsyncIterator, Callable

try:  # asyncio.CancelledError moved to BaseException in 3.8; import for clarity
    from asyncio import CancelledError
except ImportError:  # pragma: no cover
    CancelledError = Exception  # type: ignore

from .events import ev
from .runlog import RunLog


async def drive_turn(
    log: RunLog,
    events: AsyncIterator[dict],
    *,
    on_session: Callable[[str], None] | None = None,
) -> None:
    """Append every AG-UI event in `events` to `log`. On cancel, emit
    `RUN_FINISHED {stopped: true}`; on error, emit `RUN_ERROR`. Always closes
    the source generator (reaping whatever it owns, e.g. the inner claude)."""
    log.running = True
    log.run_started_at = time.time()
    log.last_tokens = None
    try:
        async for event in events:
            t = event.get("type")
            if t == "RUN_STARTED":
                # stamp the authoritative start time so a refresh/replay shows
                # the true elapsed time instead of restarting the clock at "now"
                event["started_at"] = log.run_started_at
            elif t == "SESSION" and on_session:
                on_session(event.get("session_id"))
            elif t == "RUN_TOKENS":
                log.last_tokens = {"output": event.get("output_tokens"), "input": event.get("input_tokens")}
            await log.append(event)
    except CancelledError:
        await log.append(ev("RUN_FINISHED", stopped=True))
        raise
    except Exception:  # noqa: BLE001 — surface as a terminal event, never crash the loop
        await log.append(ev("RUN_ERROR", message="run failed"))
    finally:
        try:
            await events.aclose()  # type: ignore[attr-defined]
        except Exception:  # noqa: BLE001
            pass
        log.running = False
