# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""The AG-UI event contract (Python side) — the single source of truth for the
event types this component can put on the wire. Mirror of
`typescript/src/types.ts`; kept in lockstep by the contract test.

See CONTRACT.md for field shapes.
"""
from __future__ import annotations


def ev(type_: str, **fields) -> dict:
    """Build an AG-UI event dict."""
    return {"type": type_, **fields}


# Every event type the component can emit. Grouped by origin.
EVENT_TYPES = frozenset({
    # --- emitted by translate() (the claude stream-json -> AG-UI mapping) ---
    "RUN_STARTED", "RUN_FINISHED", "RUN_ERROR",
    "TEXT_MESSAGE_START", "TEXT_MESSAGE_CONTENT", "TEXT_MESSAGE_END",
    "THINKING_START", "THINKING_CONTENT", "THINKING_END",
    "TOOL_CALL_START", "TOOL_CALL_ARGS", "TOOL_CALL_END", "TOOL_CALL_RESULT",
    "AWAIT_INPUT", "RUN_TOKENS", "RUN_STATS",
    "SESSION",        # server-internal: persisted for resume; client reducer IGNORES it
    "AUTH_REQUIRED",  # emitted on expired token; currently UNHANDLED client-side
    # --- added by the log / SSE sync layer (RunLog + sse) ---
    "SYNC", "USER_MESSAGE",
})

# Events that end a run (the driver / client treat these as terminal).
TERMINAL = frozenset({"RUN_FINISHED", "RUN_ERROR"})
