# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""The authoritative per-run event log: a store plus the run-state the SYNC
frame needs (running, started_at, last_tokens) and a frozen `seed` of prior
history.

Decoupled from any connection. The turn driver appends to it; SSE clients
subscribe to it. On a fresh process the in-memory parts are empty and `seed()`
re-hydrates history once (e.g. from a Claude transcript).
"""
from __future__ import annotations

from collections.abc import Callable

from .store import InMemoryStore, RunLogStore


class RunLog:
    def __init__(self, store: RunLogStore | None = None, *, seed: Callable[[], list[dict]] | None = None) -> None:
        self.store: RunLogStore = store or InMemoryStore()
        self._seed_fn = seed or (lambda: [])
        self._seed_items: list[dict] | None = None
        # run-state surfaced in the SYNC frame so a reconnecting client shows the
        # true running flag / elapsed time / live tokens (not reset to zero).
        self.running = False
        self.run_started_at: float | None = None     # epoch seconds
        self.last_tokens: dict | None = None          # {output, input}
        self.task = None                               # the in-flight asyncio.Task (for cancel)
        self.queue: list = []                          # prompts queued while a run is active

    @property
    def seed_items(self) -> list[dict]:
        """Frozen prior history, read once. Disjoint from live store events, so
        seed + events never double-render."""
        if self._seed_items is None:
            self._seed_items = list(self._seed_fn())
        return self._seed_items

    async def append(self, event: dict) -> int:
        return await self.store.append(event)

    async def last_seq(self) -> int:
        return await self.store.last_seq()

    def open(self, since: int):
        return self.store.open(since)
