# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""Optional seed adapter: replay prior history from Claude Code's JSONL
transcript into the SAME timeline-item shape the client reducer builds, so a
RunLog's `seed_items` can hydrate the UI directly.

This is Claude-Code-specific (the transcript format), hence an optional adapter:
apps with a different history source pass their own `seed()` to RunLog.

Item shapes (mirror typescript/src/types.ts TimelineItem):
    {kind: "user", id, text, images}
    {kind: "assistant_text", id, segments, done}
    {kind: "thinking", id, segments, done}
    {kind: "tool_call", id, name, args, result, done}
"""
from __future__ import annotations

import json
from pathlib import Path

# Claude slugs the project dir; with cwd=/app inside the sandbox it is "-app".
DEFAULT_TRANSCRIPT_DIR = Path(".rr") / "claude" / "projects" / "-app"
_IMG_NOTE = "Reference image(s) in the repo:"


def _clean_user(text: str) -> str:
    i = text.find(_IMG_NOTE)
    return text[:i].strip() if i != -1 else text


def transcript_path(workspace: Path, session_id: str, transcript_dir: Path = DEFAULT_TRANSCRIPT_DIR) -> Path | None:
    if "/" in session_id or ".." in session_id:
        return None
    return workspace / transcript_dir / f"{session_id}.jsonl"


def claude_transcript_seed(
    workspace: Path,
    session_id: str,
    transcript_dir: Path = DEFAULT_TRANSCRIPT_DIR,
) -> list[dict]:
    path = transcript_path(workspace, session_id, transcript_dir)
    if not path or not path.is_file():
        return []

    items: list[dict] = []
    tool_by_id: dict[str, dict] = {}

    with path.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                e = json.loads(line)
            except json.JSONDecodeError:
                continue
            etype = e.get("type")
            uid = e.get("uuid", "")

            if etype == "user":
                content = e.get("message", {}).get("content")
                if isinstance(content, str):
                    text = _clean_user(content)
                    if text:
                        items.append({"kind": "user", "id": uid, "text": text, "images": []})
                elif isinstance(content, list):
                    for b in content:
                        if isinstance(b, dict) and b.get("type") == "tool_result":
                            tid = b.get("tool_use_id")
                            res = b.get("content")
                            if isinstance(res, list):
                                res = "".join(c.get("text", "") for c in res if isinstance(c, dict))
                            if tid in tool_by_id:
                                tool_by_id[tid]["result"] = res if isinstance(res, str) else json.dumps(res)

            elif etype == "assistant":
                content = e.get("message", {}).get("content", [])
                if isinstance(content, list):
                    for j, b in enumerate(content):
                        if not isinstance(b, dict):
                            continue
                        t = b.get("type")
                        if t == "text" and b.get("text", "").strip():
                            items.append({"kind": "assistant_text", "id": f"{uid}-{j}", "segments": [b["text"]], "done": True})
                        elif t == "thinking" and b.get("thinking", "").strip():
                            items.append({"kind": "thinking", "id": f"{uid}-{j}", "segments": [b["thinking"]], "done": True})
                        elif t == "tool_use":
                            item = {
                                "kind": "tool_call",
                                "id": b.get("id", f"{uid}-{j}"),
                                "name": b.get("name", ""),
                                "args": json.dumps(b.get("input", {})),
                                "result": None,
                                "done": True,
                            }
                            tool_by_id[item["id"]] = item
                            items.append(item)

    return items
