# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""Resumable Server-Sent Events transport for a RunLog.

Wire protocol (see CONTRACT.md):
  1. a `SYNC` frame  (running, last_seq, seed items on a fresh load, started_at, tokens)
  2. the backlog after the client's `since`   (each `id: <seq>`)
  3. the live tail                              (each `id: <seq>`)
  4. `: ping` comments on idle so proxies don't buffer/close the stream

`sse_source` is pure (yields bytes; no web framework). `sse_response` is an
optional FastAPI convenience that wraps it in a StreamingResponse.
`resume_point(request)` reads `Last-Event-ID` (EventSource auto-reconnect) or
the `?since=` query param.
"""
from __future__ import annotations

import json
from collections.abc import AsyncIterator

from .runlog import RunLog

SSE_HEADERS = {"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}


def _frame(event: dict, seq: int | None = None) -> bytes:
    head = f"id: {seq}\n" if seq is not None else ""
    return f"{head}data: {json.dumps(event)}\n\n".encode()


async def sse_source(log: RunLog, since: int) -> AsyncIterator[bytes]:
    last = await log.last_seq()
    sync = {
        "type": "SYNC",
        "running": log.running,
        "last_seq": last,
        "items": log.seed_items if since == 0 else [],
        "started_at": log.run_started_at,
        "tokens": log.last_tokens,
    }
    yield _frame(sync)  # SYNC carries no id: it is not seq-addressable
    async for seq, event in log.open(since):
        if seq is None:
            yield b": ping\n\n"  # heartbeat
        else:
            yield _frame(event, seq)


def resume_point(request) -> int:
    """`Last-Event-ID` header (reconnect) or `?since=` query param, else 0."""
    hdr = request.headers.get("last-event-id")
    if hdr and hdr.isdigit():
        return int(hdr)
    q = request.query_params.get("since")
    return int(q) if q and q.isdigit() else 0


def sse_response(log: RunLog, since: int):
    """FastAPI convenience. Requires fastapi installed."""
    from fastapi.responses import StreamingResponse

    return StreamingResponse(sse_source(log, since), media_type="text/event-stream", headers=SSE_HEADERS)
