# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""Storage seam for the event log.

A `RunLogStore` is an append-only, seq-ordered event log with a gapless
`open(since)` (backlog-after-`since`, then live tail). Two implementations:

- `InMemoryStore` — single process (ryureflect's behavior). Fast; lost on restart.
- `RedisStreamStore` — durable + multi-process (qhive: workers are separate
  sandboxes). `seq` is an explicit monotonic counter stored per entry.

Both expose the SAME contract so the RunLog / SSE layer and the client protocol
(integer `seq`, `seq == last + 1` gap detection) are identical across them.

`open(since)` yields `(seq, event)` tuples; it also yields a heartbeat sentinel
`(None, None)` on idle so the transport can emit an SSE keep-alive ping.
"""
from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator
from typing import Protocol

HEARTBEAT_S = 15


class RunLogStore(Protocol):
    async def append(self, event: dict) -> int: ...
    async def last_seq(self) -> int: ...
    def open(self, since: int) -> AsyncIterator[tuple[int | None, dict | None]]: ...


class InMemoryStore:
    def __init__(self) -> None:
        self.events: list[dict] = []
        self._subs: set[asyncio.Queue] = set()

    async def append(self, event: dict) -> int:
        # synchronous core: append + fan-out with no await in between (no gap).
        self.events.append(event)
        seq = len(self.events)
        for q in self._subs:
            q.put_nowait((seq, event))
        return seq

    async def last_seq(self) -> int:
        return len(self.events)

    def open(self, since: int):
        # capture backlog and register the queue with NO await between them, so
        # an append can't slip through the gap between snapshot and subscribe.
        backlog = [(i + 1, e) for i, e in enumerate(self.events) if i + 1 > since]
        q: asyncio.Queue = asyncio.Queue()
        self._subs.add(q)

        async def gen():
            try:
                for item in backlog:
                    yield item
                while True:
                    try:
                        yield await asyncio.wait_for(q.get(), timeout=HEARTBEAT_S)
                    except asyncio.TimeoutError:
                        yield (None, None)  # heartbeat
            finally:
                self._subs.discard(q)

        return gen()


class RedisStreamStore:
    """Durable, multi-process log over a Redis Stream.

    `append` = INCR a per-key seq counter + XADD `{seq, data}`. `open` replays via
    XRANGE then tails via XREAD BLOCK from the last stream id (stream ordering is
    the gap guarantee across processes). Pass a `redis.asyncio` client with
    `decode_responses=True`.
    """

    def __init__(self, redis, key: str) -> None:
        self.r = redis
        self.key = key
        self._seqkey = f"{key}:seq"

    async def append(self, event: dict) -> int:
        seq = await self.r.incr(self._seqkey)
        await self.r.xadd(self.key, {"seq": seq, "data": json.dumps(event)})
        return int(seq)

    async def last_seq(self) -> int:
        val = await self.r.get(self._seqkey)
        return int(val) if val else 0

    def open(self, since: int):
        async def gen():
            last_id = "0-0"
            for sid, fields in await self.r.xrange(self.key):
                last_id = sid
                seq = int(fields["seq"])
                if seq > since:
                    yield (seq, json.loads(fields["data"]))
            while True:
                res = await self.r.xread({self.key: last_id}, block=HEARTBEAT_S * 1000, count=64)
                if not res:
                    yield (None, None)  # heartbeat
                    continue
                for _stream, msgs in res:
                    for sid, fields in msgs:
                        last_id = sid
                        yield (int(fields["seq"]), json.loads(fields["data"]))

        return gen()
