# @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

"""Translate Claude stream-json events into AG-UI protocol events.

Originally from data-llm-agent, then forked/extended in ryureflect (thinking,
tokens, stats). This is the canonical version. Stack-agnostic: it consumes an
`AsyncIterator[dict]` of Claude stream-json and yields AG-UI event dicts
(see CONTRACT.md / events.py).
"""
from __future__ import annotations

import json
import uuid
from collections.abc import AsyncIterator

from .events import ev


def _is_auth_error(text: str | None) -> bool:
    """True if `text` looks like a Claude login/auth failure (expired token)."""
    if not text:
        return False
    t = text.lower()
    return ("invalid authentication" in t) or (
        "401" in t and ("authenticat" in t or "credential" in t)
    )


async def translate(
    claude_events: AsyncIterator[dict],
    *,
    thread_id: str,
    run_id: str,
) -> AsyncIterator[dict]:
    """Consume Claude stream-json events; yield AG-UI events.

    Also yields a synthetic `SESSION` event once seen so the caller can persist
    the session id for follow-up turns.
    """
    yield ev("RUN_STARTED", thread_id=thread_id, run_id=run_id)

    current_text_msg_id: str | None = None
    block_index_to_kind: dict[int, str] = {}        # "text" | "thinking" | "tool_use"
    block_index_to_id: dict[int, str] = {}          # AG-UI id for the block
    auth_emitted = False
    turn_output = 0
    cur_output = 0
    last_input = 0

    try:
        async for event in claude_events:
            etype = event.get("type")

            if etype == "system" and event.get("subtype") == "init":
                sid = event.get("session_id")
                if sid:
                    yield ev("SESSION", session_id=sid)
                continue

            if not auth_emitted and etype == "assistant":
                content = event.get("message", {}).get("content", "")
                if isinstance(content, list):
                    content = " ".join(
                        b.get("text", "") for b in content if isinstance(b, dict)
                    )
                if _is_auth_error(content):
                    auth_emitted = True
                    yield ev("AUTH_REQUIRED")
                    continue

            if etype == "stream_event":
                inner = event.get("event", {})
                itype = inner.get("type")
                idx = inner.get("index")

                if itype == "content_block_start":
                    block = inner.get("content_block", {})
                    btype = block.get("type")
                    if btype == "text":
                        msg_id = str(uuid.uuid4())
                        block_index_to_kind[idx] = "text"
                        block_index_to_id[idx] = msg_id
                        current_text_msg_id = msg_id
                        yield ev("TEXT_MESSAGE_START", message_id=msg_id, role="assistant")
                    elif btype == "thinking":
                        msg_id = str(uuid.uuid4())
                        block_index_to_kind[idx] = "thinking"
                        block_index_to_id[idx] = msg_id
                        yield ev("THINKING_START", message_id=msg_id)
                    elif btype == "tool_use":
                        tool_call_id = block.get("id") or str(uuid.uuid4())
                        block_index_to_kind[idx] = "tool_use"
                        block_index_to_id[idx] = tool_call_id
                        yield ev(
                            "TOOL_CALL_START",
                            tool_call_id=tool_call_id,
                            tool_call_name=block.get("name", ""),
                            parent_message_id=current_text_msg_id,
                        )

                elif itype == "content_block_delta":
                    kind = block_index_to_kind.get(idx)
                    delta = inner.get("delta", {})
                    if kind == "text" and delta.get("type") == "text_delta":
                        text = delta.get("text", "")
                        if not auth_emitted and _is_auth_error(text):
                            auth_emitted = True
                            yield ev("AUTH_REQUIRED")
                            continue
                        yield ev("TEXT_MESSAGE_CONTENT", message_id=block_index_to_id[idx], delta=text)
                    elif kind == "thinking" and delta.get("type") == "thinking_delta":
                        yield ev("THINKING_CONTENT", message_id=block_index_to_id[idx], delta=delta.get("thinking", ""))
                    elif kind == "tool_use" and delta.get("type") == "input_json_delta":
                        yield ev("TOOL_CALL_ARGS", tool_call_id=block_index_to_id[idx], delta=delta.get("partial_json", ""))

                elif itype == "content_block_stop":
                    kind = block_index_to_kind.get(idx)
                    if kind == "text":
                        yield ev("TEXT_MESSAGE_END", message_id=block_index_to_id[idx])
                    elif kind == "thinking":
                        yield ev("THINKING_END", message_id=block_index_to_id[idx])
                    elif kind == "tool_use":
                        yield ev("TOOL_CALL_END", tool_call_id=block_index_to_id[idx])

                elif itype == "message_start":
                    turn_output += cur_output
                    cur_output = 0
                    usage = inner.get("message", {}).get("usage", {}) or {}
                    last_input = usage.get("input_tokens", last_input)
                elif itype == "message_delta":
                    usage = inner.get("usage", {}) or {}
                    cur_output = usage.get("output_tokens", cur_output)
                    yield ev("RUN_TOKENS", output_tokens=turn_output + cur_output, input_tokens=last_input)

                continue

            if etype == "user":
                msg = event.get("message", {})
                for block in msg.get("content", []) or []:
                    if isinstance(block, dict) and block.get("type") == "tool_result":
                        content = block.get("content")
                        if isinstance(content, list):
                            content = "".join(c.get("text", "") for c in content if isinstance(c, dict))
                        yield ev(
                            "TOOL_CALL_RESULT",
                            message_id=str(uuid.uuid4()),
                            tool_call_id=block.get("tool_use_id", ""),
                            content=content if isinstance(content, str) else json.dumps(content),
                        )
                continue

            if etype == "result":
                usage = event.get("usage") or {}
                yield ev(
                    "RUN_STATS",
                    duration_ms=event.get("duration_ms"),
                    input_tokens=usage.get("input_tokens"),
                    output_tokens=usage.get("output_tokens"),
                    cache_read_tokens=usage.get("cache_read_input_tokens"),
                    total_cost_usd=event.get("total_cost_usd"),
                    num_turns=event.get("num_turns"),
                )
                if event.get("stop_reason") == "tool_deferred":
                    deferred = event.get("deferred_tool_use") or {}
                    if deferred.get("name") == "AskUserQuestion":
                        yield ev(
                            "AWAIT_INPUT",
                            tool_call_id=deferred.get("id", ""),
                            questions=(deferred.get("input") or {}).get("questions", []),
                        )
                    continue
                if event.get("is_error"):
                    msg = event.get("result", "unknown error")
                    if not auth_emitted and _is_auth_error(msg):
                        auth_emitted = True
                        yield ev("AUTH_REQUIRED")
                    else:
                        yield ev("RUN_ERROR", message=msg)
                continue

    finally:
        yield ev("RUN_FINISHED", thread_id=thread_id, run_id=run_id)
