// @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

import type { AGUIEvent } from './types'

// Parse an SSE stream from a `fetch` POST and yield AG-UI events. Use this when
// you trigger a turn with a body and want to consume the same stream inline
// (e.g. a one-shot POST that streams its own response). For the resumable,
// reconnecting read stream, prefer `subscribeAGUI` (EventSource + Last-Event-ID).
export async function* streamAGUI(
  url: string,
  body: unknown,
  signal?: AbortSignal,
): AsyncGenerator<AGUIEvent> {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal,
  })
  if (!res.ok || !res.body) throw new Error(`stream failed: ${res.status}`)

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let buf = ''

  while (true) {
    const { value, done } = await reader.read()
    if (done) break
    buf += decoder.decode(value, { stream: true })

    let sep: number
    while ((sep = buf.indexOf('\n\n')) !== -1) {
      const frame = buf.slice(0, sep)
      buf = buf.slice(sep + 2)
      for (const line of frame.split('\n')) {
        if (line.startsWith('data:')) {
          const json = line.slice(5).trim()
          if (!json) continue
          try {
            yield JSON.parse(json) as AGUIEvent
          } catch {
            // ignore malformed frames
          }
        }
      }
    }
  }
}
