// @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

// The client reducer: fold an AG-UI event stream into a timeline. Pure function,
// framework-agnostic (use with useReducer, a Zustand store action, or plain
// state). Mirror of the events the Python translate() can emit.

import type { AGUIEvent, RunStats, TimelineItem } from './types'

export type ChatState = {
  items: TimelineItem[]
  running: boolean
  tokens: { output: number; input: number } | null
  runStartedAt: number | null // epoch ms; authoritative so elapsed survives refresh
}

export const initialChatState: ChatState = { items: [], running: false, tokens: null, runStartedAt: null }

const rid = () =>
  typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : String(Math.random())

export function applyEvent(state: ChatState, ev: AGUIEvent): ChatState {
  switch (ev.type) {
    case 'RUN_STARTED':
      // use the server-stamped start time (epoch seconds) so a refresh/replay
      // shows true elapsed time; fall back to now only if it's missing.
      return {
        ...state,
        running: true,
        tokens: null,
        runStartedAt: ev.started_at ? ev.started_at * 1000 : Date.now(),
      }

    case 'RUN_FINISHED':
    case 'RUN_ERROR':
      return { ...state, running: false }

    case 'RUN_TOKENS':
      return { ...state, tokens: { output: ev.output_tokens, input: ev.input_tokens } }

    case 'TEXT_MESSAGE_START':
      return { ...state, items: [...state.items, { kind: 'assistant_text', id: ev.message_id, segments: [], done: false }] }

    case 'TEXT_MESSAGE_CONTENT':
      if (!ev.delta) return state
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'assistant_text' && it.id === ev.message_id ? { ...it, segments: [...it.segments, ev.delta] } : it,
        ),
      }

    case 'TEXT_MESSAGE_END':
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'assistant_text' && it.id === ev.message_id ? { ...it, done: true } : it,
        ),
      }

    case 'THINKING_START':
      return { ...state, items: [...state.items, { kind: 'thinking', id: ev.message_id, segments: [], done: false }] }

    case 'THINKING_CONTENT':
      if (!ev.delta) return state
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'thinking' && it.id === ev.message_id ? { ...it, segments: [...it.segments, ev.delta] } : it,
        ),
      }

    case 'THINKING_END':
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'thinking' && it.id === ev.message_id ? { ...it, done: true } : it,
        ),
      }

    case 'TOOL_CALL_START':
      return {
        ...state,
        items: [...state.items, { kind: 'tool_call', id: ev.tool_call_id, name: ev.tool_call_name, args: '', done: false }],
      }

    case 'TOOL_CALL_ARGS':
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'tool_call' && it.id === ev.tool_call_id ? { ...it, args: it.args + ev.delta } : it,
        ),
      }

    case 'TOOL_CALL_END':
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'tool_call' && it.id === ev.tool_call_id ? { ...it, done: true } : it,
        ),
      }

    case 'TOOL_CALL_RESULT':
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'tool_call' && it.id === ev.tool_call_id ? { ...it, result: ev.content } : it,
        ),
      }

    case 'AWAIT_INPUT':
      return {
        ...state,
        items: state.items.map((it) =>
          it.kind === 'tool_call' && it.id === ev.tool_call_id ? { ...it, awaiting: true, questions: ev.questions } : it,
        ),
      }

    case 'RUN_STATS':
      return { ...state, items: [...state.items, { kind: 'stats', id: rid(), stats: ev as RunStats }] }

    // server-authoritative sync: SYNC seeds history (only when non-empty, so a
    // reconnect with items:[] never wipes the timeline); USER_MESSAGE echoes the
    // user's own turn to every client.
    case 'SYNC':
      return {
        ...state,
        items: ev.items.length ? ev.items : state.items,
        running: ev.running,
        runStartedAt: ev.running ? (ev.started_at ? ev.started_at * 1000 : state.runStartedAt) : state.runStartedAt,
        tokens: ev.running ? (ev.tokens ?? state.tokens) : state.tokens,
      }

    case 'USER_MESSAGE':
      return pushUser(state, ev.text, ev.images)

    // SESSION (server-internal) and AUTH_REQUIRED (handle in your UI if you want
    // an auth banner) intentionally fall through.
    default:
      return state
  }
}

export function pushUser(state: ChatState, text: string, images: string[] = []): ChatState {
  return { ...state, items: [...state.items, { kind: 'user', id: rid(), text, images }] }
}
