// @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

import type { AGUIEvent } from './types'

// Subscribe to a resumable AG-UI SSE endpoint. Opens an EventSource, tracks the
// monotonic `seq` from each frame's id, and on a gap (seq != last + 1) reopens
// from the last good seq. On network drop the browser auto-reconnects with
// `Last-Event-ID`, which the server replays from. Framework-agnostic: pass an
// `onEvent` callback (dispatch into a Zustand store, a reducer, anything).
//
//   const sub = subscribeAGUI(`/threads/${id}/events`, (ev) => store.apply(ev))
//   // later: sub.close()

export type Subscription = { close: () => void }

export function subscribeAGUI(url: string, onEvent: (ev: AGUIEvent) => void): Subscription {
  let es: EventSource | null = null
  let closed = false
  let lastSeq = 0
  const sep = url.includes('?') ? '&' : '?'

  function open(since: number) {
    if (closed) return
    es?.close()
    lastSeq = since // next expected seq is since+1 (the backlog/live that follows)
    es = new EventSource(`${url}${sep}since=${since}`)
    es.onmessage = (e: MessageEvent) => {
      let ev: AGUIEvent
      try {
        ev = JSON.parse(e.data)
      } catch {
        return
      }
      // SYNC carries the pre-log seed + run-state and has NO seq. Apply it, but
      // leave lastSeq at `since` so the backlog that follows (since+1 ..) applies
      // in order instead of looking like a gap. (Setting lastSeq = ev.last_seq
      // here makes the very first backlog frame trip the gap check, which silently
      // drops the whole backlog on a fresh load.)
      if (ev.type === 'SYNC') {
        onEvent(ev)
        return
      }
      if (e.lastEventId) {
        const seq = Number(e.lastEventId)
        if (seq && seq !== lastSeq + 1) {
          open(lastSeq) // genuine gap -> reopen from last good seq
          return
        }
        lastSeq = seq
      }
      onEvent(ev)
    }
  }

  open(0)
  return {
    close: () => {
      closed = true
      es?.close()
    },
  }
}
