// @generated by agui-sync -- DO NOT EDIT. Edit in agui-sync and run scripts/sync.sh.

// The AG-UI event contract (TypeScript side). Single source of truth for the
// event union; mirror of python/agui_sync/events.py (kept in lockstep by the
// contract test). See CONTRACT.md for field shapes.

export type QuestionOption = { label: string; description?: string }
export type Question = {
  question: string
  header?: string
  multiSelect?: boolean
  options?: QuestionOption[]
}

export type RunStats = {
  type: 'RUN_STATS'
  duration_ms: number | null
  input_tokens: number | null
  output_tokens: number | null
  cache_read_tokens: number | null
  total_cost_usd: number | null
  num_turns: number | null
}

export type AGUIEvent =
  | { type: 'RUN_STARTED'; thread_id: string; run_id: string; started_at?: number }
  | { type: 'RUN_FINISHED'; thread_id?: string; run_id?: string; stopped?: boolean }
  | { type: 'RUN_ERROR'; message: string }
  | { type: 'TEXT_MESSAGE_START'; message_id: string; role: 'assistant' }
  | { type: 'TEXT_MESSAGE_CONTENT'; message_id: string; delta: string }
  | { type: 'TEXT_MESSAGE_END'; message_id: string }
  | { type: 'THINKING_START'; message_id: string }
  | { type: 'THINKING_CONTENT'; message_id: string; delta: string }
  | { type: 'THINKING_END'; message_id: string }
  | { type: 'TOOL_CALL_START'; tool_call_id: string; tool_call_name: string; parent_message_id: string | null }
  | { type: 'TOOL_CALL_ARGS'; tool_call_id: string; delta: string }
  | { type: 'TOOL_CALL_END'; tool_call_id: string }
  | { type: 'TOOL_CALL_RESULT'; message_id: string; tool_call_id: string; content: string }
  | { type: 'AWAIT_INPUT'; tool_call_id: string; questions: Question[] }
  | RunStats
  | { type: 'RUN_TOKENS'; output_tokens: number; input_tokens: number }
  | { type: 'SESSION'; session_id: string } // server-internal; reducer ignores it
  | { type: 'AUTH_REQUIRED' } // emitted on expired token; currently unhandled
  // server-authoritative sync frames (added by the log/SSE layer)
  | { type: 'USER_MESSAGE'; text: string; images: string[] }
  | {
      type: 'SYNC'
      running: boolean
      last_seq: number
      items: TimelineItem[]
      started_at?: number | null
      tokens?: { output: number; input: number } | null
    }

// ---- timeline items the reducer builds ----
export type UserItem = { kind: 'user'; id: string; text: string; images?: string[] }
export type AssistantTextItem = { kind: 'assistant_text'; id: string; segments: string[]; done: boolean }
export type ThinkingItem = { kind: 'thinking'; id: string; segments: string[]; done: boolean }
export type ToolCallItem = {
  kind: 'tool_call'
  id: string
  name: string
  args: string
  result?: string | null
  done: boolean
  awaiting?: boolean
  questions?: Question[]
}
export type StatsItem = { kind: 'stats'; id: string; stats: RunStats }
export type TimelineItem = UserItem | AssistantTextItem | ThinkingItem | ToolCallItem | StatsItem
